# CSV Data Cleaning - Review SY-08002944

**Objective**: Clean and organize data from Review_SY-08002944_4_3_2025 10_31_21.csv

**Data Source**: Code/DSCwashumed/backend/data/Review_SY-08002944_4_3_2025 10_31_21.csv

**Output**: Cleaned data files in cleadned_data folder

**Process**: Load → Analyze → Clean → Export

In [8]:
# Import libraries
import pandas as pd
import numpy as np
from pathlib import Path
import matplotlib.pyplot as plt
import seaborn as sns

# Data paths
data_file = Path("Review_SY-08002944_4_3_2025 10_31_21.csv")
output_dir = Path("cleadned_data")
output_dir.mkdir(exist_ok=True)

print(f"Data file: {data_file}")
print(f"Output directory: {output_dir}")
print(f"Data file exists: {data_file.exists()}")

Data file: Review_SY-08002944_4_3_2025 10_31_21.csv
Output directory: cleadned_data
Data file exists: True

## Data Loading and Initial Analysis

In [ ]:
# Load the CSV data
def load_csv_data():
    try:
        df = pd.read_csv(data_file)
        print(f"Shape: {df.shape}")
        return df
    except Exception as e:
        print(f"Error loading data: {e}")
        return None

# Load data
raw_df = load_csv_data()

if raw_df is not None:
    raw_df.head()

Data loaded successfully!
Shape: (25, 43)
Columns: ['Sample ID', 'Patient ID', 'Patient', 'WBC (10^3/uL)', 'Neu # (10^3/uL)', 'Lym # (10^3/uL)', 'Mon # (10^3/uL)', 'Eos # (10^3/uL)', 'Bas # (10^3/uL)', 'Neu % (%)', 'Lym % (%)', 'Mon % (%)', 'Eos % (%)', 'Bas % (%)', 'RBC (10^6/uL)', 'HGB (g/dL)', 'HCT (%)', 'MCV (fL)', 'MCH (pg)', 'MCHC (g/dL)', 'RDW-CV (%)', 'PLT (10^3/uL)', 'MPV (fL)', 'Species', 'Sample State', 'Owner Last Name', 'Mode', 'Date', 'Time', 'Gender', 'Age', 'Ref. Group', 'Draw Date', 'Draw Time', 'Delivery Date', 'Delivery Time', 'Veterinarian', 'Operator', 'Comments', 'WBC Message', 'RBC Message', 'PLT Message', 'Unnamed: 42']

First few rows:

,Sample ID,Patient ID,Patient,WBC (10^3/uL),Neu # (10^3/uL),Lym # (10^3/uL),Mon # (10^3/uL),Eos # (10^3/uL),Bas # (10^3/uL),Neu % (%),...,Draw Time,Delivery Date,Delivery Time,Veterinarian,Operator,Comments,WBC Message,RBC Message,PLT Message,Unnamed: 42
0,5410,NaN,NaN,H 13.42,2.50,H 9.81,0.66,0.34,0.11,18.7,...,NaN,NaN,NaN,NaN,Schuettpelz,NaN,Leukocytosis,NaN,NaN,NaN
1,5409,NaN,NaN,H 11.14,1.41,H 8.99,0.50,0.18,0.06,12.7,...,NaN,NaN,NaN,NaN,Schuettpelz,NaN,NaN,NaN,NaN,NaN
2,5408,NaN,NaN,H 12.75,2.46,H 9.14,0.84,0.22,0.09,19.3,...,NaN,NaN,NaN,NaN,Schuettpelz,NaN,Leukocytosis,NaN,NaN,NaN
3,5407,NaN,NaN,H 13.50,3.31,H 9.56,0.41,0.13,0.09,24.5,...,NaN,NaN,NaN,NaN,Schuettpelz,NaN,Leukocytosis,NaN,NaN,NaN
4,5406,NaN,NaN,H 20.72,H 4.26,H 14.39,H 1.60,0.36,0.11,20.6,...,NaN,NaN,NaN,NaN,Schuettpelz,NaN,Leukocytosis\nLymphocytosis,NaN,NaN,NaN

Data types:
Sample ID           object
Patient ID         float64
Patient            float64
WBC (10^3/uL)       object
Neu # (10^3/uL)     object
Lym # (10^3/uL)     object
Mon # (10^3/uL)     object
Eos # (10^3/uL)     object
Bas # (10^3/uL)     object
Neu % (%)           object
Lym % (%)           object
Mon % (%)           object
Eos % (%)           object
Bas % (%)           object
RBC (10^6/uL)       object
HGB (g/dL)          object
HCT (%)             object
MCV (fL)            object
MCH (pg)            object
MCHC (g/dL)         object
RDW-CV (%)          object
PLT (10^3/uL)       object
MPV (fL)            object
Species             object
Sample State        object
Owner Last Name    float64
Mode                object
Date                object
Time                object
Gender             float64
Age                float64
Ref. Group          object
Draw Date          float64
Draw Time          float64
Delivery Date      float64
Delivery Time      float64
Veterinarian       float64
Operator            object
Comments           float64
WBC Message         object
RBC Message         object
PLT Message         object
Unnamed: 42        float64
dtype: object

Basic info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 43 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Sample ID        25 non-null     object
 1   Patient ID       0 non-null      float64
 2   Patient          0 non-null      float64
 3   WBC (10^3/uL)    25 non-null     object
 4   Neu # (10^3/uL)  25 non-null     object
 5   Lym # (10^3/uL)  25 non-null     object
 6   Mon # (10^3/uL)  25 non-null     object
 7   Eos # (10^3/uL)  25 non-null     object
 8   Bas # (10^3/uL)  25 non-null     object
 9   Neu % (%)        25 non-null     object
 10  Lym % (%)        25 non-null     object
 11  Mon % (%)        25 non-null     object
 12  Eos % (%)        25 non-null     object
 13  Bas % (%)        25 non-null     object
 14  RBC (10^6/uL)    25 non-null     object
 15  HGB (g/dL)       25 non-null     object
 16  HCT (%)          25 non-null     object
 17  MCV (fL)         25 non-null     object
 18  MCH (pg)         25 non-null     object
 19  MCHC (g/dL)      25 non-null     object
 20  RDW-CV (%)       25 non-null     object
 21  PLT (10^3/uL)    25 non-null     object
 22  MPV (fL)         25 non-null     object
 23  Species          25 non-null     object
 24  Sample State     25 non-null     object
 25  Owner Last Name  0 non-null      float64
 26  Mode             25 non-null     object
 27  Date             25 non-null     object
 28  Time             25 non-null     object
 29  Gender           0 non-null      float64
 30  Age              0 non-null      float64
 31  Ref. Group       25 non-null     object
 32  Draw Date        0 non-null      float64
 33  Draw Time        0 non-null      float64
 34  Delivery Date    0 non-null      float64
 35  Delivery Time    0 non-null      float64
 36  Veterinarian     0 non-null      float64
 37  Operator         25 non-null     object
 38  Comments         0 non-null      float64
 39  WBC Message      15 non-null     object
 40  RBC Message      5 non-null      object
 41  PLT Message      4 non-null      object
 42  Unnamed: 42      0 non-null      float64
dtypes: float64(12), object(31)
memory usage: 8.5+ KB
None

## Data Quality Assessment

In [ ]:
# Analyze data quality
def analyze_data_quality(df):
    missing_counts = df.isnull().sum()
    missing_percent = (missing_counts / len(df)) * 100
    duplicates = df.duplicated().sum()
    
    print(f"Missing values by column:")
    for col in df.columns:
        if missing_counts[col] > 0:
            print(f"  {col}: {missing_counts[col]} ({missing_percent[col]:.1f}%)")
    
    print(f"Duplicate rows: {duplicates}")
    
    return missing_counts, missing_percent

if raw_df is not None:
    missing_counts, missing_percent = analyze_data_quality(raw_df)

=== DATA QUALITY ASSESSMENT ===

Missing Values:
  Patient ID: 25 (100.0%)
  Patient: 25 (100.0%)
  Owner Last Name: 25 (100.0%)
  Gender: 25 (100.0%)
  Age: 25 (100.0%)
  Draw Date: 25 (100.0%)
  Draw Time: 25 (100.0%)
  Delivery Date: 25 (100.0%)
  Delivery Time: 25 (100.0%)
  Veterinarian: 25 (100.0%)
  Comments: 25 (100.0%)
  WBC Message: 10 (40.0%)
  RBC Message: 20 (80.0%)
  PLT Message: 21 (84.0%)
  Unnamed: 42: 25 (100.0%)

Duplicate rows: 0

Column Analysis:
  Sample ID: 24 unique values, dtype: object
  Patient ID: 0 unique values, dtype: float64
  Patient: 0 unique values, dtype: float64
  WBC (10^3/uL): 25 unique values, dtype: object
  Neu # (10^3/uL): 25 unique values, dtype: object
  Lym # (10^3/uL): 24 unique values, dtype: object
  Mon # (10^3/uL): 22 unique values, dtype: object
  Eos # (10^3/uL): 18 unique values, dtype: object
    Values: [' 0.34 ', ' 0.18 ', ' 0.22 ', ' 0.13 ', ' 0.36 ', ' 0.00 ', ' 0.30 ', ' 0.12 ', ' 0.21 ', ' 0.24 ', ' 0.06 ', ' 0.11 ', 'H 0.72 ', ' 0.05 ', ' 0.47 ', 'H 0.60 ', ' 0.37 ', ' ***** ']
  Bas # (10^3/uL): 15 unique values, dtype: object
    Values: [' 0.11 ', ' 0.06 ', ' 0.09 ', 'H 0.14 ', ' 0.00 ', ' 0.07 ', ' 0.05 ', ' 0.08 ', ' 0.04 ', 'H 0.18 ', 'H 0.46 ', ' 0.03 ', 'H 0.21 ', 'H 0.26 ', ' ***** ']
  Neu % (%): 23 unique values, dtype: object
  Lym % (%): 25 unique values, dtype: object
  Mon % (%): 21 unique values, dtype: object
  Eos % (%): 18 unique values, dtype: object
    Values: [' 2.5 ', ' 1.6 ', ' 1.7 ', ' 1.0 ', ' 3.6 ', ' 2.3 ', ' 0.9 ', ' 1.3 ', ' 1.2 ', ' 0.5 ', ' 1.5 ', ' 0.8 ', ' 5.6 ', ' 3.3 ', 'H 12.8 ', 'H 13.3 ', 'H 14.9 ', ' ***** ']
  Bas % (%): 14 unique values, dtype: object
    Values: [' 0.8 ', ' 0.6 ', ' 0.7 ', ' 0.5 ', ' 0.9 ', ' 0.4 ', ' 0.3 ', ' 1.0 ', 'H 3.6 ', 'H 2.6 ', 'H 5.6 ', 'H 5.8 ', 'H 3.0 ', ' ***** ']
  RBC (10^6/uL): 20 unique values, dtype: object
    Values: [' 8.91 ', ' 8.71 ', ' 8.18 ', ' 9.04 ', ' 8.87 ', 'L 0.16 ', ' 8.30 ', ' 8.49 ', ' 8.56 ', ' 9.79 ', ' 9.46 ', ' 9.67 ', ' 10.00 ', ' 9.98 ', ' 9.70 ', ' 9.35 ', ' 8.58 ', ' 8.36 ', 'L 0.00 ', 'L 0.01 ']
  HGB (g/dL): 19 unique values, dtype: object
    Values: [' 14.6 ', ' 14.0 ', ' 13.6 ', ' 14.4 ', ' 13.1 ', 'L 0.3 ', ' 13.4 ', ' 14.1 ', ' 15.9 ', ' 15.4 ', ' 15.7 ', ' 15.8 ', ' 15.3 ', ' 14.7 ', ' 13.0 ', ' 11.3 ', ' 12.9 ', ' 12.6 ', 'L 0.0 ']
  HCT (%): 20 unique values, dtype: object
    Values: [' 43.8 ', ' 42.9 ', ' 41.8 ', ' 44.7 ', ' 41.1 ', ' 44.4 ', 'L 0.0 ', ' 40.7 ', ' 43.7 ', ' 46.8 ', ' 45.8 ', ' 47.1 ', ' 47.9 ', ' 46.1 ', ' 45.6 ', ' 43.9 ', ' 37.7 ', 'L 32.6 ', ' 37.0 ', ' 35.8 ']
  MCV (fL): 19 unique values, dtype: object
    Values: [' 49.2 ', ' 51.1 ', ' 49.5 ', ' 50.3 ', ' 50.1 ', ' ***** ', ' 49.0 ', ' 51.5 ', ' 51.0 ', ' 47.8 ', ' 48.5 ', ' 48.7 ', ' 47.9 ', ' 46.2 ', ' 47.0 ', ' 44.0 ', 'L 36.6 ', ' 41.5 ', ' 42.8 ']
  MCH (pg): 13 unique values, dtype: object
    Values: [' 16.3 ', ' 16.1 ', ' 16.6 ', ' 16.0 ', ' 16.2 ', ' ***** ', ' 16.9 ', ' 15.8 ', ' 15.9 ', ' 15.7 ', ' 15.1 ', 'L 12.7 ', ' 14.4 ']
  MCHC (g/dL): 17 unique values, dtype: object
    Values: [' 33.2 ', ' 32.7 ', ' 32.5 ', ' 32.3 ', ' 32.0 ', ' 32.4 ', ' ***** ', ' 32.8 ', ' 33.1 ', ' 34.0 ', ' 33.5 ', ' 33.3 ', ' 33.0 ', ' 34.4 ', ' 33.6 ', ' 34.7 ', ' 35.2 ']
  RDW-CV (%): 19 unique values, dtype: object
    Values: [' 14.9 ', ' 15.5 ', ' 16.3 ', ' 14.3 ', ' 17.1 ', ' ***** ', 'H 19.8 ', ' 14.7 ', ' 14.2 ', ' 13.2 ', ' 15.2 ', ' 13.6 ', ' 14.4 ', ' 12.8 ', ' 13.4 ', ' 14.5 ', 'H 26.7 ', ' 17.9 ', ' 15.7 ']
  PLT (10^3/uL): 25 unique values, dtype: object
  MPV (fL): 11 unique values, dtype: object
    Values: [' 4.8 ', ' 4.7 ', ' 4.6 ', ' 5.0 ', ' 5.1 ', ' 4.9 ', ' 5.2 ', ' 5.6 ', ' 5.3 ', 'H 7.3 ', ' ***** ']
  Species: 1 unique values, dtype: object
    Values: ['Mouse']
  Sample State: 1 unique values, dtype: object
    Values: ['Printed']
  Owner Last Name: 0 unique values, dtype: float64
  Mode: 1 unique values, dtype: object
    Values: ['Whole Blood']
  Date: 1 unique values, dtype: object
    Values: ['04-01-2025']
  Time: 25 unique values, dtype: object
  Gender: 0 unique values, dtype: float64
  Age: 0 unique values, dtype: float64
  Ref. Group: 1 unique values, dtype: object
    Values: ['Mouse Default']
  Draw Date: 0 unique values, dtype: float64
  Draw Time: 0 unique values, dtype: float64
  Delivery Date: 0 unique values, dtype: float64
  Delivery Time: 0 unique values, dtype: float64
  Veterinarian: 0 unique values, dtype: float64
  Operator: 2 unique values, dtype: object
    Values: ['Schuettpelz', 'Magee']
  Comments: 0 unique values, dtype: float64
  WBC Message: 5 unique values, dtype: object
    Values: ['Leukocytosis', nan, 'Leukocytosis\nLymphocytosis', 'Leukopenia\nNeutropenia\nLymphopenia', 'Leukocytosis\nBasophilia\nEosinophilia', 'Basophilia']
  RBC Message: 2 unique values, dtype: object
    Values: [nan, 'Anemia', 'Microcytosis']
  PLT Message: 1 unique values, dtype: object
    Values: [nan, 'Thrombocytopenia']
  Unnamed: 42: 0 unique values, dtype: float64

## Data Cleaning

In [11]:
# Clean the data
def clean_csv_data(df):
    df_clean = df.copy()
    
    # Remove duplicate rows
    df_clean = df_clean.drop_duplicates()
    
    # Clean column names
    df_clean.columns = df_clean.columns.str.strip().str.replace(' ', '_').str.replace('[^a-zA-Z0-9_]', '', regex=True)
    
    # Handle missing values for lab data appropriately
    numeric_cols = df_clean.select_dtypes(include=[np.number]).columns
    categorical_cols = df_clean.select_dtypes(include=['object']).columns
    
    # For numeric lab values, use median imputation
    for col in numeric_cols:
        if df_clean[col].isnull().sum() > 0:
            if df_clean[col].notna().sum() > 0:
                median_val = df_clean[col].median()
                df_clean[col] = df_clean[col].fillna(median_val)
            else:
                df_clean[col] = df_clean[col].fillna(0)
    
    # For categorical values, use "Unknown"
    for col in categorical_cols:
        if df_clean[col].isnull().sum() > 0:
            df_clean[col] = df_clean[col].fillna("Unknown")
    
    # Convert data types where appropriate
    for col in df_clean.columns:
        if df_clean[col].dtype == 'object':
            try:
                numeric_series = pd.to_numeric(df_clean[col], errors='coerce')
                if not numeric_series.isnull().all():
                    df_clean[col] = numeric_series
            except:
                pass
    
    return df_clean

if raw_df is not None:
    cleaned_df = clean_csv_data(raw_df)
    cleaned_df.head()

## Data Validation

In [12]:
# Validate cleaned data
def validate_cleaned_data(df):
    missing_values = df.isnull().sum().sum()
    duplicate_rows = df.duplicated().sum()
    
    print(f"Missing values: {missing_values}")
    print(f"Duplicate rows: {duplicate_rows}")
    print(f"Shape: {df.shape}")
    
    return df.describe()

if 'cleaned_df' in locals() and cleaned_df is not None:
    summary_stats = validate_cleaned_data(cleaned_df)
    summary_stats

Missing values: 119
Duplicate rows: 0
Shape: (25, 43)

## Export Cleaned Data

In [13]:
# Export cleaned data to cleadned_data folder
def export_cleaned_data(df):
    base_name = "Review_SY-08002944_cleaned"
    csv_output = output_dir / f"{base_name}.csv"
    excel_output = output_dir / f"{base_name}.xlsx"
    
    # Export to CSV
    df.to_csv(csv_output, index=False)
    
    # Export to Excel with multiple sheets
    with pd.ExcelWriter(excel_output, engine='openpyxl') as writer:
        df.to_excel(writer, sheet_name='Cleaned_Data', index=False)
        
        numeric_cols = df.select_dtypes(include=[np.number]).columns
        if len(numeric_cols) > 0:
            summary_stats = df[numeric_cols].describe()
            summary_stats.to_excel(writer, sheet_name='Summary_Statistics')
        
        info_data = {
            'Column': df.columns,
            'Data_Type': [str(dtype) for dtype in df.dtypes],
            'Non_Null_Count': [df[col].count() for col in df.columns],
            'Null_Count': [df[col].isnull().sum() for col in df.columns],
            'Unique_Values': [df[col].nunique() for col in df.columns]
        }
        info_df = pd.DataFrame(info_data)
        info_df.to_excel(writer, sheet_name='Data_Info', index=False)
    
    print(f"Files exported to {output_dir}")
    return csv_output, excel_output

if 'cleaned_df' in locals() and cleaned_df is not None:
    csv_path, excel_path = export_cleaned_data(cleaned_df)

Files exported to cleadned_data